'use client'

import { useState, useEffect, useCallback } from 'react'
import { useParams, useRouter } from 'next/navigation'
import AdminLayout from '@/components/ui/AdminLayout'
import { withAuth, useAuth } from '@/contexts/AuthContext'
import { isPathHiddenForAccount } from '@/lib/auth/special-accounts'
import { TokenManager } from '@/lib/api-client'
import {
  Calendar,
  Clock,
  AlertTriangle,
  CheckCircle,
  RefreshCw,
  BarChart3,
  RotateCcw,
  ArrowLeft,
  TrendingUp,
} from 'lucide-react'

interface WeeklyTaskSummary {
  user_id: string
  user_name: string
  week_start: string
  week_end: string
  total_tasks: number
  completed_tasks: number
  in_progress_tasks: number
  pending_tasks: number
  completion_rate: number
  self_tasks: number
  subsidy_tasks: number
  high_priority_completed: number
  medium_priority_completed: number
  low_priority_completed: number
  completed_task_details: Array<{
    id: string
    title: string
    business_name: string
    task_type: string
    status: string
    completed_at: string
    priority: string
  }>
  pending_task_details: Array<{
    id: string
    title: string
    business_name: string
    task_type: string
    status: string
    due_date?: string
    priority: string
    days_overdue?: number
  }>
  average_completion_time_days: number
  overdue_tasks: number
  created_at: string
}

// 전체리포트관리 페이지와 동일한 업무 타입 매핑
const taskTypeConfig: Record<string, { label: string; color: string }> = {
  self: { label: '자비', color: 'bg-blue-100 text-blue-700' },
  subsidy: { label: '보조금', color: 'bg-green-100 text-green-700' },
  as: { label: 'AS', color: 'bg-orange-100 text-orange-700' },
  dealer: { label: '대리점', color: 'bg-purple-100 text-purple-700' },
  etc: { label: '기타', color: 'bg-gray-100 text-gray-600' },
  outsourcing: { label: '외주', color: 'bg-pink-100 text-pink-700' },
}

const priorityConfig: Record<string, { label: string; color: string }> = {
  high: { label: '높음', color: 'text-red-600' },
  medium: { label: '보통', color: 'text-yellow-600' },
  low: { label: '낮음', color: 'text-green-600' },
}

function getPerformanceColor(rate: number): string {
  if (rate >= 80) return 'text-green-700'
  if (rate >= 60) return 'text-yellow-700'
  return 'text-red-700'
}

function formatDate(dateStr: string): string {
  return new Date(dateStr).toLocaleDateString('ko-KR', {
    month: 'short',
    day: 'numeric',
  })
}

function formatDateLong(dateStr: string): string {
  return new Date(dateStr).toLocaleDateString('ko-KR', {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
  })
}

// 전체리포트관리 페이지와 동일한 StatCard 컴포넌트
function StatCard({ icon: Icon, label, value, color }: {
  icon: React.ElementType
  label: string
  value: number | string
  color: string
}) {
  const colorMap: Record<string, string> = {
    blue: 'bg-blue-50 text-blue-600',
    purple: 'bg-purple-50 text-purple-600',
    green: 'bg-green-50 text-green-600',
    yellow: 'bg-yellow-50 text-yellow-600',
    red: 'bg-red-50 text-red-600',
    gray: 'bg-gray-50 text-gray-500',
  }
  return (
    <div className="bg-white rounded-md shadow-sm border border-gray-200 p-2.5 sm:p-3 md:p-4">
      <div className="flex items-center gap-2 md:gap-3">
        <div className={`w-8 h-8 md:w-10 md:h-10 ${colorMap[color] || 'bg-gray-50 text-gray-500'} rounded-md flex items-center justify-center flex-shrink-0`}>
          <Icon className="w-4 h-4 md:w-5 md:h-5" />
        </div>
        <div className="min-w-0">
          <div className="text-base sm:text-lg md:text-xl font-bold text-gray-900 leading-none">{value}</div>
          <div className="text-[10px] sm:text-xs text-gray-500 mt-0.5 truncate">{label}</div>
        </div>
      </div>
    </div>
  )
}

function UserWeeklyReportDetailPage() {
  const params = useParams()
  const router = useRouter()
  const userId = params?.userId as string
  const { user, permissions } = useAuth()

  useEffect(() => {
    if (user?.email && permissions?.isSpecialAccount && isPathHiddenForAccount(user.email, '/admin/weekly-reports')) {
      router.replace('/admin/business')
    }
  }, [user, permissions])

  const [report, setReport] = useState<WeeklyTaskSummary | null>(null)
  const [loading, setLoading] = useState(false)
  const [selectedWeek, setSelectedWeek] = useState('')
  const [dataSource, setDataSource] = useState<'database' | 'generated' | null>(null)
  const [isAutoGenerated, setIsAutoGenerated] = useState(false)

  useEffect(() => {
    if (typeof window !== 'undefined') {
      const urlParams = new URLSearchParams(window.location.search)
      const weekDateParam = urlParams.get('weekDate')

      if (weekDateParam) {
        setSelectedWeek(weekDateParam)
      } else {
        const today = new Date()
        const sunday = new Date(today.setDate(today.getDate() - today.getDay()))
        setSelectedWeek(sunday.toISOString().split('T')[0])
      }
    }
  }, [userId])

  const fetchWeeklyReport = useCallback(async (forceRegenerate = false) => {
    if (!selectedWeek || !userId) return

    setLoading(true)
    try {
      const url = `/api/weekly-reports?userId=${userId}&weekDate=${selectedWeek}${forceRegenerate ? '&forceRegenerate=true' : ''}`
      const token = TokenManager.getToken()
      const response = await fetch(url, {
        headers: { 'Authorization': `Bearer ${token}` }
      })
      const data = await response.json()

      if (data.success) {
        const reportData = data.data.report

        const hasCompletedDetails = reportData.completed_task_details && reportData.completed_task_details.length > 0
        const hasPendingDetails = reportData.pending_task_details && reportData.pending_task_details.length > 0
        const hasTaskDetails = hasCompletedDetails || hasPendingDetails

        if (!hasTaskDetails && reportData.total_tasks > 0 && !forceRegenerate) {
          fetchWeeklyReport(true)
          return
        }

        setReport(reportData)
        setDataSource(data.data.summary?.data_source || null)
        setIsAutoGenerated(data.data.summary?.is_auto_generated || false)

        if (forceRegenerate) {
          alert('리포트가 재생성되었습니다.')
        }
      } else {
        alert('리포트 조회에 실패했습니다.')
      }
    } catch {
      alert('리포트 조회 중 오류가 발생했습니다.')
    } finally {
      setLoading(false)
    }
  }, [selectedWeek, userId])

  useEffect(() => {
    if (selectedWeek && userId) {
      fetchWeeklyReport()
    }
  }, [selectedWeek, userId, fetchWeeklyReport])

  return (
    <AdminLayout
      title="주간 리포트 상세"
      description="사용자별 주간 업무 성과 및 진행 상황 상세 분석"
    >
      <div className="space-y-4 md:space-y-6">

        {/* 컨트롤 영역 — 전체리포트관리와 동일한 1줄 레이아웃 */}
        <div className="bg-white rounded-md shadow-sm border border-gray-200 px-3 py-2">
          <div className="flex items-center gap-2">
            {/* 뒤로가기 */}
            <button
              onClick={() => {
                const weekDateParam = selectedWeek ? `?weekDate=${selectedWeek}` : ''
                router.push(`/admin/weekly-reports/admin${weekDateParam}`)
              }}
              className="flex items-center gap-1 text-xs text-gray-500 hover:text-gray-800 transition-colors flex-shrink-0"
            >
              <ArrowLeft className="w-3.5 h-3.5" />
              <span className="hidden sm:inline">전체 리포트</span>
            </button>

            <div className="w-px h-5 bg-gray-200 flex-shrink-0" />

            {/* 날짜 선택 */}
            <Calendar className="w-3.5 h-3.5 text-gray-400 flex-shrink-0" />
            <input
              type="date"
              value={selectedWeek}
              onChange={(e) => setSelectedWeek(e.target.value)}
              className="w-36 px-2 py-1.5 border border-gray-300 rounded-md text-xs focus:ring-2 focus:ring-blue-500 focus:border-transparent flex-shrink-0"
            />

            {/* 데이터 소스 배지 */}
            {dataSource && (
              <span className={`px-2 py-0.5 text-[10px] rounded-full flex-shrink-0 ${
                dataSource === 'database' ? 'bg-green-100 text-green-700' : 'bg-blue-100 text-blue-700'
              }`}>
                {dataSource === 'database' ? `저장됨${isAutoGenerated ? ' (자동)' : ''}` : '실시간'}
              </span>
            )}

            <div className="flex-1" />

            {/* 재생성 버튼 */}
            {report && (
              <button
                onClick={() => fetchWeeklyReport(true)}
                disabled={loading}
                className="flex items-center gap-1 px-2.5 py-1.5 text-xs bg-gray-100 text-gray-600 rounded-md hover:bg-gray-200 disabled:opacity-50 transition-colors flex-shrink-0"
              >
                <RotateCcw className="w-3 h-3" />
                <span className="hidden sm:inline">재생성</span>
              </button>
            )}

            {/* 조회 버튼 */}
            <button
              onClick={() => fetchWeeklyReport(false)}
              disabled={loading}
              className="flex items-center gap-1.5 px-3 py-1.5 text-xs bg-blue-600 text-white rounded-md hover:bg-blue-700 disabled:opacity-50 transition-colors flex-shrink-0"
            >
              <RefreshCw className={`w-3.5 h-3.5 ${loading ? 'animate-spin' : ''}`} />
              {loading ? '조회중' : '조회'}
            </button>
          </div>
        </div>

        {/* 리포트 내용 */}
        {report ? (
          <>
            {/* 헤더 — 이름 + 주간 + 완료율 */}
            <div className="bg-white rounded-md shadow-sm border border-gray-200 px-3 py-2.5 sm:px-4 sm:py-3">
              <div className="flex items-center justify-between gap-3">
                <div className="flex items-center gap-2.5 min-w-0">
                  <div className="w-8 h-8 rounded-full bg-blue-100 text-blue-700 flex items-center justify-center flex-shrink-0 text-sm font-bold">
                    {report.user_name.charAt(0)}
                  </div>
                  <div className="min-w-0">
                    <div className="text-sm font-semibold text-gray-900">{report.user_name}님의 주간 리포트</div>
                    <div className="text-[10px] text-gray-400 mt-0.5">
                      {formatDateLong(report.week_start)} – {formatDateLong(report.week_end)}
                    </div>
                  </div>
                </div>
                <div className="flex-shrink-0 text-right">
                  <div className={`text-xl font-bold ${getPerformanceColor(report.completion_rate)}`}>
                    {report.completion_rate}%
                  </div>
                  <div className="text-[10px] text-gray-400">완료율</div>
                </div>
              </div>
            </div>

            {/* 통계 카드 — 전체리포트관리와 동일한 StatCard */}
            <div className="grid grid-cols-2 sm:grid-cols-4 gap-2 sm:gap-3">
              <StatCard icon={BarChart3} label="총 업무" value={report.total_tasks} color="blue" />
              <StatCard icon={CheckCircle} label="완료" value={report.completed_tasks} color="green" />
              <StatCard icon={Clock} label={`평균 ${report.average_completion_time_days}일`} value={report.in_progress_tasks} color="yellow" />
              <StatCard icon={AlertTriangle} label="연체" value={report.overdue_tasks} color="red" />
            </div>

            {/* 진행 현황 — 콤팩트 카드 */}
            <div className="bg-white rounded-md shadow-sm border border-gray-200 p-3 sm:p-4">
              <div className="text-xs font-medium text-gray-700 mb-3">업무 진행 현황</div>
              <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
                {/* 상태별 */}
                <div className="space-y-2">
                  <div className="text-[10px] font-medium text-gray-500 uppercase tracking-wide">상태별</div>
                  {[
                    { label: '완료', value: report.completed_tasks, color: 'bg-green-500' },
                    { label: '진행중', value: report.in_progress_tasks, color: 'bg-blue-500' },
                    { label: '대기', value: report.pending_tasks, color: 'bg-gray-400' },
                  ].map(({ label, value, color }) => (
                    <div key={label} className="flex items-center gap-2">
                      <span className="text-xs text-gray-600 w-12 flex-shrink-0">{label}</span>
                      <div className="flex-1 bg-gray-100 rounded-full h-1.5">
                        <div
                          className={`${color} h-1.5 rounded-full transition-all`}
                          style={{ width: report.total_tasks > 0 ? `${(value / report.total_tasks) * 100}%` : '0%' }}
                        />
                      </div>
                      <span className="text-xs font-medium text-gray-700 w-5 text-right flex-shrink-0">{value}</span>
                    </div>
                  ))}
                </div>
                {/* 타입별 */}
                <div className="space-y-2">
                  <div className="text-[10px] font-medium text-gray-500 uppercase tracking-wide">업무 유형별</div>
                  {[
                    { label: '자비', value: report.self_tasks, color: 'bg-blue-500' },
                    { label: '보조금', value: report.subsidy_tasks, color: 'bg-green-500' },
                    { label: '기타', value: report.total_tasks - report.self_tasks - report.subsidy_tasks, color: 'bg-gray-400' },
                  ].map(({ label, value, color }) => (
                    <div key={label} className="flex items-center gap-2">
                      <span className="text-xs text-gray-600 w-12 flex-shrink-0">{label}</span>
                      <div className="flex-1 bg-gray-100 rounded-full h-1.5">
                        <div
                          className={`${color} h-1.5 rounded-full transition-all`}
                          style={{ width: report.total_tasks > 0 ? `${(value / report.total_tasks) * 100}%` : '0%' }}
                        />
                      </div>
                      <span className="text-xs font-medium text-gray-700 w-5 text-right flex-shrink-0">{value}</span>
                    </div>
                  ))}
                </div>
              </div>
            </div>

            {/* 완료된 업무 목록 */}
            {report.completed_task_details.length > 0 && (
              <div className="bg-white rounded-md shadow-sm border border-gray-200 overflow-hidden">
                <div className="flex items-center gap-2 px-3 sm:px-4 py-2.5 border-b border-gray-100">
                  <CheckCircle className="w-3.5 h-3.5 text-green-600 flex-shrink-0" />
                  <span className="text-xs font-medium text-gray-700">
                    완료된 업무 <span className="text-gray-400">({report.completed_task_details.length}개)</span>
                  </span>
                </div>

                {/* 데스크탑: 테이블 */}
                <div className="hidden md:block overflow-x-auto">
                  <table className="w-full table-fixed text-xs">
                    <thead>
                      <tr className="bg-gray-50 border-b border-gray-100">
                        <th className="text-left px-4 py-2 text-xs font-medium text-gray-500 w-20">유형</th>
                        <th className="text-left px-4 py-2 text-xs font-medium text-gray-500 w-[30%]">사업장</th>
                        <th className="text-left px-4 py-2 text-xs font-medium text-gray-500">업무명</th>
                        <th className="text-left px-4 py-2 text-xs font-medium text-gray-500 w-16">우선순위</th>
                        <th className="text-left px-4 py-2 text-xs font-medium text-gray-500 w-24">완료일</th>
                      </tr>
                    </thead>
                    <tbody className="divide-y divide-gray-50">
                      {report.completed_task_details.map((task) => {
                        const typeInfo = taskTypeConfig[task.task_type] || taskTypeConfig.etc
                        const priorityInfo = priorityConfig[task.priority] || priorityConfig.medium
                        return (
                          <tr key={task.id} className="hover:bg-gray-50 transition-colors">
                            <td className="px-4 py-2.5">
                              <span className={`inline-flex items-center px-1.5 py-0.5 rounded text-[11px] font-medium ${typeInfo.color}`}>
                                {typeInfo.label}
                              </span>
                            </td>
                            <td className="px-4 py-2.5 font-medium text-gray-900 text-sm truncate">{task.business_name}</td>
                            <td className="px-4 py-2.5 text-gray-600 truncate">{task.title}</td>
                            <td className="px-4 py-2.5">
                              <span className={`text-[11px] font-medium ${priorityInfo.color}`}>{priorityInfo.label}</span>
                            </td>
                            <td className="px-4 py-2.5 text-gray-400 text-xs whitespace-nowrap">
                              {formatDate(task.completed_at)}
                            </td>
                          </tr>
                        )
                      })}
                    </tbody>
                  </table>
                </div>

                {/* 모바일: 카드 목록 */}
                <div className="md:hidden divide-y divide-gray-100">
                  {report.completed_task_details.map((task) => {
                    const typeInfo = taskTypeConfig[task.task_type] || taskTypeConfig.etc
                    const priorityInfo = priorityConfig[task.priority] || priorityConfig.medium
                    return (
                      <div key={task.id} className="px-3 py-2.5 flex items-start gap-2.5">
                        <span className={`inline-flex items-center px-1.5 py-0.5 rounded text-[10px] font-medium flex-shrink-0 mt-0.5 ${typeInfo.color}`}>
                          {typeInfo.label}
                        </span>
                        <div className="flex-1 min-w-0">
                          <div className="text-xs font-medium text-gray-900 truncate">{task.business_name}</div>
                          <div className="text-[10px] text-gray-500 truncate mt-0.5">{task.title}</div>
                          <div className="flex items-center gap-2 mt-1">
                            <span className={`text-[10px] font-medium ${priorityInfo.color}`}>{priorityInfo.label}</span>
                            <span className="text-[10px] text-gray-400">{formatDate(task.completed_at)}</span>
                          </div>
                        </div>
                      </div>
                    )
                  })}
                </div>
              </div>
            )}

            {/* 미완료 업무 목록 */}
            {report.pending_task_details.length > 0 && (
              <div className="bg-white rounded-md shadow-sm border border-gray-200 overflow-hidden">
                <div className="flex items-center gap-2 px-3 sm:px-4 py-2.5 border-b border-gray-100">
                  <Clock className="w-3.5 h-3.5 text-yellow-600 flex-shrink-0" />
                  <span className="text-xs font-medium text-gray-700">
                    미완료 업무 <span className="text-gray-400">({report.pending_task_details.length}개)</span>
                  </span>
                  {report.overdue_tasks > 0 && (
                    <span className="ml-auto flex items-center gap-1 text-[10px] text-red-600 font-medium">
                      <AlertTriangle className="w-3 h-3" />
                      {report.overdue_tasks}건 연체
                    </span>
                  )}
                </div>

                {/* 데스크탑: 테이블 */}
                <div className="hidden md:block overflow-x-auto">
                  <table className="w-full table-fixed text-xs">
                    <thead>
                      <tr className="bg-gray-50 border-b border-gray-100">
                        <th className="text-left px-4 py-2 text-xs font-medium text-gray-500 w-20">유형</th>
                        <th className="text-left px-4 py-2 text-xs font-medium text-gray-500 w-[30%]">사업장</th>
                        <th className="text-left px-4 py-2 text-xs font-medium text-gray-500">업무명</th>
                        <th className="text-left px-4 py-2 text-xs font-medium text-gray-500 w-16">우선순위</th>
                        <th className="text-left px-4 py-2 text-xs font-medium text-gray-500 w-28">마감일 / 연체</th>
                      </tr>
                    </thead>
                    <tbody className="divide-y divide-gray-50">
                      {report.pending_task_details.map((task) => {
                        const typeInfo = taskTypeConfig[task.task_type] || taskTypeConfig.etc
                        const priorityInfo = priorityConfig[task.priority] || priorityConfig.medium
                        const isOverdue = task.days_overdue && task.days_overdue > 0
                        return (
                          <tr key={task.id} className={`hover:bg-gray-50 transition-colors ${isOverdue ? 'bg-red-50/40' : ''}`}>
                            <td className="px-4 py-2.5">
                              <span className={`inline-flex items-center px-1.5 py-0.5 rounded text-[11px] font-medium ${typeInfo.color}`}>
                                {typeInfo.label}
                              </span>
                            </td>
                            <td className="px-4 py-2.5 font-medium text-gray-900 text-sm truncate">{task.business_name}</td>
                            <td className="px-4 py-2.5 text-gray-600 truncate">{task.title}</td>
                            <td className="px-4 py-2.5">
                              <span className={`text-[11px] font-medium ${priorityInfo.color}`}>{priorityInfo.label}</span>
                            </td>
                            <td className="px-4 py-2.5 text-xs whitespace-nowrap">
                              {isOverdue ? (
                                <span className="inline-flex items-center gap-0.5 px-1.5 py-0.5 bg-red-100 text-red-700 rounded text-[10px] font-medium">
                                  {task.days_overdue}일 연체
                                </span>
                              ) : task.due_date ? (
                                <span className="text-gray-400">{formatDate(task.due_date)}</span>
                              ) : (
                                <span className="text-gray-300">—</span>
                              )}
                            </td>
                          </tr>
                        )
                      })}
                    </tbody>
                  </table>
                </div>

                {/* 모바일: 카드 목록 */}
                <div className="md:hidden divide-y divide-gray-100">
                  {report.pending_task_details.map((task) => {
                    const typeInfo = taskTypeConfig[task.task_type] || taskTypeConfig.etc
                    const priorityInfo = priorityConfig[task.priority] || priorityConfig.medium
                    const isOverdue = task.days_overdue && task.days_overdue > 0
                    return (
                      <div key={task.id} className={`px-3 py-2.5 flex items-start gap-2.5 ${isOverdue ? 'bg-red-50/40' : ''}`}>
                        <span className={`inline-flex items-center px-1.5 py-0.5 rounded text-[10px] font-medium flex-shrink-0 mt-0.5 ${typeInfo.color}`}>
                          {typeInfo.label}
                        </span>
                        <div className="flex-1 min-w-0">
                          <div className="text-xs font-medium text-gray-900 truncate">{task.business_name}</div>
                          <div className="text-[10px] text-gray-500 truncate mt-0.5">{task.title}</div>
                          <div className="flex items-center gap-2 mt-1 flex-wrap">
                            <span className={`text-[10px] font-medium ${priorityInfo.color}`}>{priorityInfo.label}</span>
                            {isOverdue ? (
                              <span className="inline-flex items-center px-1 py-0.5 bg-red-100 text-red-700 rounded text-[10px] font-medium">
                                {task.days_overdue}일 연체
                              </span>
                            ) : task.due_date ? (
                              <span className="text-[10px] text-gray-400">마감 {formatDate(task.due_date)}</span>
                            ) : null}
                          </div>
                        </div>
                      </div>
                    )
                  })}
                </div>
              </div>
            )}

            {/* 완료/미완료 모두 없을 때 */}
            {report.completed_task_details.length === 0 && report.pending_task_details.length === 0 && (
              <div className="bg-white rounded-md shadow-sm border border-gray-200 p-10 text-center">
                <TrendingUp className="w-10 h-10 text-gray-200 mx-auto mb-2" />
                <p className="text-xs text-gray-400">해당 주간 업무 상세 내역이 없습니다</p>
              </div>
            )}
          </>
        ) : (
          <div className="bg-white rounded-md shadow-sm border border-gray-200 p-10 text-center">
            <Calendar className="w-12 h-12 text-gray-300 mx-auto mb-3" />
            <p className="text-sm text-gray-500">주간을 선택하고 조회 버튼을 클릭하세요</p>
          </div>
        )}

      </div>
    </AdminLayout>
  )
}

export default withAuth(UserWeeklyReportDetailPage, undefined, 3)
